{
 "title": "Spark-Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "executorProcessUuid",
    "query": "select  distinct \"processUuid\" from \"metrics\".\"autogen\".\"CpuAndMemory\" where \"role\" = 'executor'  AND  time > now() - 5m"
   },
   {
    "name": "timeInterval",
    "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Driver Current Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"heapMemoryTotalUsed\" as Used from \"metrics\".\"autogen\".\"CpuAndMemory\"  where  \"role\" = 'driver'  AND time > now() -$timeInterval",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Driver Current Process CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"processCpuLoad\" as process from \"metrics\".\"autogen\".\"CpuAndMemory\"  where  \"role\" = 'driver'  AND time > now() -$timeInterval",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executor Current Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"heapMemoryTotalUsed\" as Used from \"metrics\".\"autogen\".\"CpuAndMemory\"  where  \"processUuid\" =~ /^$executorProcessUuid$/ AND time > now() -$timeInterval",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executor Current Process CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"processCpuLoad\" as process from \"metrics\".\"autogen\".\"CpuAndMemory\"  where  \"processUuid\" =~ /^$executorProcessUuid$/ AND time > now() -$timeInterval ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Driver Heap Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"memoryPools-EdenSpace-usageUsed\" as EdenSpace, \"memoryPools-SurvivorSpace-usageUsed\" as  SurvivorSpace, \"memoryPools-TenuredGen-usageUsed\" as  TenuredGen from \"metrics\".\"autogen\".\"CpuAndMemory\"  where \"role\"='driver' AND time > now() -$timeInterval",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Driver Non-Heap Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"memoryPools-CodeCache-usageUsed\" as CodeCache, \"memoryPools-CompressedClassSpace-usageUsed\" as  CompressedClassSpace, \"memoryPools-Metaspace-usageUsed\" as  Metaspace from \"metrics\".\"autogen\".\"CpuAndMemory\"  where \"role\"='driver' AND time > now() -$timeInterval",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Driver GC Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"gc-Copy-collectionTime\" as Copy, \"gc-MarkSweepCompact-collectionTime\" as  MarkSweepCompact from \"metrics\".\"autogen\".\"CpuAndMemory\"  where \"role\"='driver' AND time > now() - 30m ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executor Heap Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"memoryPools-EdenSpace-usageUsed\" as EdenSpace, \"memoryPools-SurvivorSpace-usageUsed\" as  SurvivorSpace, \"memoryPools-TenuredGen-usageUsed\" as  TenuredGen from \"metrics\".\"autogen\".\"CpuAndMemory\"  where \"processUuid\" =~ /^$executorProcessUuid$/ AND time > now() -$timeInterval",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executor Non-Heap Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"memoryPools-CodeCache-usageUsed\" as CodeCache, \"memoryPools-CompressedClassSpace-usageUsed\" as  CompressedClassSpace, \"memoryPools-Metaspace-usageUsed\" as  Metaspace from \"metrics\".\"autogen\".\"CpuAndMemory\"  where \"processUuid\" =~ /^$executorProcessUuid$/ AND time > now() -$timeInterval ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executor GC Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"gc-Copy-collectionTime\" as Copy, \"gc-MarkSweepCompact-collectionTime\" as  MarkSweepCompact from \"metrics\".\"autogen\".\"CpuAndMemory\"  where \"processUuid\" =~ /^$executorProcessUuid$/ AND time > now() - 30m ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executor Committed And Used Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"heapMemoryCommitted\" as Committed, \"heapMemoryTotalUsed\" as Used from \"metrics\".\"autogen\".\"CpuAndMemory\"  where   \"processUuid\" =~ /^$executorProcessUuid$/ AND time > now() -$timeInterval ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Driver Committed and Used Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"heapMemoryCommitted\" as Committed, \"heapMemoryTotalUsed\" as Used from \"metrics\".\"autogen\".\"CpuAndMemory\"  where  \"role\" = 'driver' AND time > now() -$timeInterval",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executor Direct Buffer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 19 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"bufferPools-direct-memoryUsed\" as Used, \"bufferPools-direct-totalCapacity\" as  Capacity from \"metrics\".\"autogen\".\"CpuAndMemory\"  where \"processUuid\" =~ /^$executorProcessUuid$/ AND time > now() - 30m ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executor IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": " select  /^stat-idle.*/,/^stat-iowait.*/,/^stat-nice.*/,/^stat-system.*/,/^stat-user.*/ from \"metrics\".\"autogen\".\"IO\" where \"processUuid\" =~ /^$executorProcessUuid$/ AND time > now() - 1h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executor Threads",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 26 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select  \"host\", \"threadName\", \"threadState\"  from \"metrics\".\"autogen\".\"Stacktrace\" where \"processUuid\" =~ /^$executorProcessUuid$/ AND (\"threadState\" = 'WAITING' OR \"threadState\" = 'BLOCKED' ) AND time > now() - 10m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}